name: Build And Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Allow Git safe directory
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        git config --global --add safe.directory "C:/E/Semester 6/SCD/app/actions-runner/_work/SCDProjectRepo/SCDProjectRepo"
      shell: powershell

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to Minikube's environment
      run: |
        Write-Output "Configuring Docker to use Minikube's daemon..."
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression
      shell: powershell

    - name: Build Docker image
      run: |
        docker build -t i222683abdullah/app:latest .
      shell: powershell

    - name: Login to Docker Hub
      run: |
        "0d37aba1@" | docker login -u "i222683abdullah" --password-stdin
      shell: powershell

    - name: Push Docker image to Docker Hub
      run: |
        docker push i222683abdullah/app:latest
      shell: powershell

    - name: Create namespace if not exists
      run: |
        kubectl create namespace my-app-ns --dry-run=client -o yaml | kubectl apply -f -
      shell: powershell

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml -n my-app-ns
        kubectl apply -f service.yaml -n my-app-ns
      shell: powershell