name: Build And Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: [self-hosted, windows, x64]

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Docker to use Minikube daemon
      run: |
        for /f "tokens=*" %%i in ('minikube -p minikube docker-env --shell cmd') do call %%i

    - name: Build Docker image
      run: docker build -t i222683abdullah/app:latest .

    - name: Login to Docker Hub
      run: echo 0d37aba1@ | docker login -u i222683abdullah --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push i222683abdullah/app:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
